### ISSUE TITLE
Doesn't work with Blender 2.80 nightly

### ISSUE THREAD

**Issue by garyo** [ksons/gltf-blender-importer#27]
Using the latest Blender nightly as of 3 May 2018, I installed the addon and importing a gltf gives the following error: 
`AttributeError: 'bpy_prop_collection' object has no attribute 'link'`
This is in `io_scene_gltf/node.py` line 111 in `create_root_objects`.

This may be helpful: https://wiki.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes

**Comment by polarathene** [comment]
Still an issue, full error I have:

```
Traceback (most recent call last):
  File "/usr/share/blender/2.80/scripts/addons/io_scene_gltf/__init__.py", line 195, in execute
    node.create_hierarchy(self)
  File "/usr/share/blender/2.80/scripts/addons/io_scene_gltf/node.py", line 149, in create_hierarchy
    if not create_scenes(op):
  File "/usr/share/blender/2.80/scripts/addons/io_scene_gltf/node.py", line 141, in create_scenes
    create_root_objects(op, roots, blender_scene)
  File "/usr/share/blender/2.80/scripts/addons/io_scene_gltf/node.py", line 111, in create_root_objects
    scene.objects.link(root_object)
AttributeError: 'bpy_prop_collection' object has no attribute 'link'

location: <unknown location>:-1
```

**Comment by scurest** [comment]
2.8 support is mainlined to master now. v0.5.0 supports the 2.8 beta (as of January 31 anyway).
